# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/korei/.zshrc'
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select

alias ls="ls --color=auto"
alias rec="byzanz-record --height=1080 --width=1920"
alias sw="$HOME/.config/i3/i3-master-layout/i3-swallow-stack.py"

bindkey "^[[1~"   beginning-of-line
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey "^[[4~"   end-of-line
bindkey  "^[[3~"  delete-char
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey '^[^?' backward-kill-word

setopt PROMPT_CR
setopt PROMPT_SP
export PROMPT_EOL_MARK=""

autoload -Uz compinit
compinit
# End of lines added by compinstall

eval "$(starship init zsh)"

fastfetch -l void

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
