#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# if [[ -z $DISPLAY && $(tty) == /dev/tty1 && $XDG_SESSION_TYPE == tty ]]; then
#   MOZ_ENABLE_WAYLAND=1 QT_QPA_PLATFORM=xcb QT_QPA_PLATFORMTHEME=qt5ct SDL_VIDEODRIVER=x11 XDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session
# fi

export BROWSER=chromium
export EDITOR=nvim
