#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DVI-D-1 -d 11 12 13 14 15 16 17 18 19

bspc config border_width        3
bspc config window_gap          6
bspc config top_padding         0
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"
bspc config focused_border_color "#674ea7"
bspc config presel_feedback_color "#000000"


# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating follow=on
bspc rule -a imv state=floating follow=on
bspc rule -a GParted state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

killall -q pipewire
killall -q mpris-proxy
killall -q wireplumber
killall -q polkit-gnome-au

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
xset r rate 300 30
setxkbmap -layout us,ru,ua
~/.config/polybar/launch.sh
nm-applet &
blueman-applet &
picom --experimental-backends &
nitrogen --restore &
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/wireplumber &
mpris-proxy &
/usr/bin/dunst &
